# encoding: UTF-8
#<% require 'kitchen-sync' %>
---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_zero

platforms:
- name: centos-6
- name: fedora-21
- name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[baseos::default]
